#!/usr/bin/env bash

archinstall --config ./archlinux/user_configuration/json

ansible-pull -t ssh -U https://github.com/cobbles/.dotfiles.git

git clone https://github.com/cobbles/.dotfiles.git ~/.dotfiles
cd ~/.dotfiles

ansible-playbook local.yml
