#!/usr/bin/env bash

archinstall --silent --config ./archinstall/user_configuration.json

# git clone https://github.com/cobbles/.dotfiles.git ~/.dotfiles
# cd ~/.dotfiles

# ansible-playbook $@ local.yml
