#!/usr/bin/env bash
if ! [[ `git fetch` && `git status | grep "up to date"` ]]; then
    echo -n "[.dotfiles] Would you like to update? [Y/n] "
    read option
    [[ "$option" = $'\n' ]] || echo
    case "$option" in
      [yY$'\n']) ~/.dotfiles/setup --pull-latest ;;
    esac
fi
