#!/usr/bin/env bash

## Install
sudo apt-add-repository -y ppa:ansible/ansible
sudo apt-get update
sudo apt-get install -y ansible

## Runs the local.yml playbook from the git repo
ansible-pull -U https://github.com/cobbles/ansible.git
