#!/usr/bin/env bash

# Dracula Theme Ansi256 colors
background="\e[38;5;59m"
currentLine="\e[38;5;60m"
foreground="\e[38;5;231m"
comment="\e[38;5;103m"
cyan="\e[38;5;159m"
green="\e[38;5;120m"
orange="\e[38;5;222m"
pink="\e[38;5;212m"
purple="\e[38;5;183m" 
red="\e[38;5;210m"
yellow="\e[38;5;229m"
reset="\e[0m"

currDir=$PWD

currentCommit=$(git rev-parse HEAD)
pullLatest=false

while [[ $# -gt 0 ]]; do
  case $1 in
    --pull-latest)
        pullLatest=true
  esac
  shift
done

function show_banner() {
    echo -e "${purple}"
    cat << "EOF"
       __________  ____  ____  __    ___________
      / ____/ __ \/ __ )/ __ )/ /   / ____/ ___/
     / /   / / / / __  / __  / /   / __/  \__ \
    / /___/ /_/ / /_/ / /_/ / /___/ /___ ___/ /
    \____/\____/_____/_____/_____/_____//____/
EOF
    echo -e "${reset}"
    echo -e "${cyan}               cobbles dotfiles${reset}"
    echo -e "${comment}          https://github.com/cobbles/.dotfiles${reset}"
    echo ""
}


function pull_latest() {
    dir=~/.dotfiles
    if [[ $pullLatest = true ]] then
        echo -e " ${purple}Pulling latest changes...${reset}"
        cd $dir
        git add -A
        git stash
        git pull
        cd $currDir
    fi
}

function generate_ssh_key() {
    file=~/.ssh/id_rsa

    echo -e "🔐 ${purple}Generating new ssh key...${reset}"
    [ -f $file ] && echo -e "${green}   $file already exists... skipping.${reset}" && return

    ssh-keygen -t ed25519 -N "" -f $file
}

function install_yay() {
    dir=~/yay-bin

    echo -e "📦 ${purple}Installing yay...${reset}"
    [ -d $dir ] && echo -e "${green}   $dir already exists... skipping.${reset}" && return

    sudo pacman -S --needed git base-devel
    git clone https://aur.archlinux.org/yay-bin.git $dir
    cd $dir
    makepkg -si
    cd $currDir
}

function install_aur_packages() {
    echo -e "📦 ${purple}Installing aur packages...${reset}"

    cat ~/.dotfiles/aur_packages | xargs yay -S --noconfirm --answerdiff=None --answeredit=None
}

function stow_dotfiles() {
    echo -e "📁 ${purple}Running stow on dotfiles...${reset}"
    stow -R -d ~/.dotfiles -t ~/ files
}

function show_commit_summary() {
    dir=~/.dotfiles
    if [[ $pullLatest = true ]] then
        echo -e "📋 ${purple}Changes:${reset}"
        cd $dir
        git --no-pager log --pretty=format:'[%C(yellow)%h%Creset]    %C(blue)%s%Creset' $currentCommit..HEAD
        echo ""
        cd $currDir
    fi
}

function post_install() {
    chsh -s /bin/zsh
    zplug install
}

show_banner
pull_latest
generate_ssh_key
install_yay
install_aur_packages
stow_dotfiles
post_install
show_commit_summary

