#!/usr/bin/env bash

# Install
sudo apt-get install -y software-properties-common git
sudo apt-add-repository -y ppa:ansible/ansible
sudo apt-get update
sudo apt-get install -y ansible

ansible-pull -t ssh -U https://github.com/cobbles/.dotfiles.git

git clone https://github.com/cobbles/.dotfiles.git ~/.dotfiles
cd ~/.dotfiles
ansible-playbook local.yml