#!/usr/bin/env bash

# Install
sudo apt-get install -y software-properties-common git wget curl
sudo apt-add-repository -y ppa:ansible/ansible
sudo apt-get update
sudo apt-get install -y ansible

git clone https://github.com/cobbles/.dotfiles.git ~/.dotfiles
cd ~/.dotfiles

ansible-playbook $@ local.yml
