---
- name: firefox snap packages
  become: true
  snap:
    name: firefox
    state: absent
    options:
      - purge=true

- name: snap-store
  become: true
  snap:
    name: snap-store
    state: absent
    options:
      - purge=true

- name: get gnome snaps
  become: true
  shell: snap list | awk '!/^Name|^core/ {print $1}' | grep gnome || true
  register: snaps

- name: gnome snaps
  become: true
  snap:
    name: "{{ item }}"
    state: absent
    options:
      - purge=true
  loop: "{{ snaps.stdout_lines }}"

- name: gtk-common-themes
  become: true
  snap:
    name: gtk-common-themes
    state: absent
    options:
      - purge=true

- name: snapd-desktop-integration
  become: true
  snap:
    name: snapd-desktop-integration
    state: absent
    options:
      - purge=true

- name: bare
  become: true
  snap:
    name: bare
    state: absent
    options:
      - purge=true

- name: get core snaps
  become: true
  shell: snap list | awk '!/^Name/ {print $1}' | grep core || true
  register: snaps

- name: remove core snaps
  become: true
  snap:
    name: "{{ item }}"
    state: absent
    options:
      - purge=true
  loop: "{{ snaps.stdout_lines }}"

- name: remove snapd
  become: true
  snap:
    name: snapd
    state: absent
    options:
      - purge=true

- name: remove snapd from apt
  become: true
  apt:
    name: snapd
    state: absent
    autoremove: true

- name: Make apt the prefered install method
  shell: |
    echo '
    Package: snapd
    Pin: release a=*
    Pin-Priority: -10
    ' | sudo tee /etc/apt/preferences.d/nosnap.pref

- name: update apt cache
  become: true
  apt:
    update_cache: true