- name: clone gtk dracula theme
  git:
    repo: https://github.com/dracula/gtk
    dest: ~/dracula-themes/gtk

- name: ensure .icons dir exists
  file:
    dest: ~/.icons
    state: directory

- name: ensure ~/.themes/gtk dir exists
  file:
    dest: ~/.themes/gtk
    state: directory

- name: download gtk icons
  unarchive:
    src: https://github.com/dracula/gtk/files/5214870/Dracula.zip
    dest: ~/.icons
    remote_src: yes

- name: stow gtk theme
  args:
    chdir: ~/dracula-themes/
  command: stow -t ~/.themes/gtk gtk

- name: stow gtk
  args:
    chdir: "{{ role_path }}/files"
  command: stow -t ~/ gtk
