- name: clone i3dracula theme
  git:
    repo: https://github.com/dracula/i3.git
    dest: ~/dracula-themes/i3

- name: clone rofi dracula theme
  git:
    repo: https://github.com/dracula/rofi
    dest: ~/dracula-themes/rofi

- name: stow autorandr
  args:
    chdir: "{{ role_path }}/files"
  command: stow -t ~/ autorandr

- name: stow i3
  args:
    chdir: "{{ role_path }}/files"
  command: stow -t ~/ i3

- name: stow rofi
  args:
    chdir: "{{ role_path }}/files"
  command: stow -t ~/ rofi
