- name: remove ~/.zshrc
  file:
    path: ~/.zshrc
    state: absent

- name: create symlink for dracula theme
  file:
    src: ~/dracula-themes/zsh/dracula.zsh-theme
    dest: ~/.oh-my-zsh/themes/dracula.zsh-theme
    state: link

- name: stow
  args:
    chdir: "{{ role_path }}"
  command: stow -t ~/ files
