- name: ssh
  include_tasks:
    file: ssh.yml
    apply:
      tags:
        - always
  tags:
    - always

- name: Check if ~/ansible exists
  stat:
    path: ~/ansible
  register: dir
  tags: always

- name: clone anisble repo
  when: dir.stat.exists == false
  git:
    repo: git@github.com:cobbles/ansible.git
    dest: ~/ansible
    accept_newhostkey: true
    clone: true
  tags: always

- name: alacritty
  include_tasks:
    file: alacritty.yml
    apply:
      tags:
        - alacritty
  tags:
    - alacritty

- name: firefox
  include_tasks:
    file: firefox.yml
    apply:
      tags:
        - firefox
  tags:
    - firefox

- name: gtk
  include_tasks:
    file: gtk.yml
    apply:
      tags:
        - gtk
  tags:
    - gtk

- name: intellihr
  include_tasks:
    file: intellihr.yml
    apply:
      tags:
        - intellihr
  tags:
    - intellihr

- name: zsh
  include_tasks:
    file: zsh.yml
    apply:
      tags:
        - zsh
  tags:
    - zsh

- name: sway
  include_tasks:
    file: sway.yml
    apply:
      tags:
        - sway
  tags:
    - sway
