- name: remove ~/.zshrc
  file:
    path: ~/.zshrc
    state: absent

- name: stow zsh
  args:
    chdir: "{{ role_path }}/files"
  command: stow -t ~/ zsh

- name: zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

- name: zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

- name: clone fzf
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: ~/.fzf

- name: install fzf
  shell: ~/.fzf/install

- name: clone zsh dracula theme
  git:
    repo: https://github.com/dracula/zsh.git
    dest: ~/dracula-themes/zsh

- name: create symlink for dracula theme
  file:
    src: ~/dracula-themes/zsh/dracula.zsh-theme
    dest: ~/.oh-my-zsh/themes/dracula.zsh-theme
    state: link

