- name: .ssh dir exists
  file:
    dest: ~/.ssh
    mode: 0700
    state: directory

- name: ~/.ssh/id_rsa exists
  stat:
    path: ~/.ssh/id_rsa
  register: dir

- name: install ssh private key
  when: dir.stat.exists == false
  copy:
    src: id_rsa
    dest: ~/.ssh/id_rsa
    mode: 0600

- name: install ssh public key
  when: dir.stat.exists == false
  copy:
    src: id_rsa.pub
    dest: ~/.ssh/id_rsa.pub
    mode: 0644
