workspace $ws1 output $preferLeft
workspace $ws2 output $preferCenter
workspace $ws3 output $preferCenter
workspace $ws4 output $preferCenter
workspace $ws5 output $preferCenter
workspace $ws6 output $preferCenter
workspace $ws7 output $preferCenter
workspace $ws8 output $preferCenter
workspace $ws9 output $preferCenter
workspace $ws10 output $preferLeft
