- name: Add alacritty PPA
  become: true
  apt_repository:
    repo: ppa:aslatter/ppa
  tags:
    - alacritty
- name: Install Alacritty
  become: true
  apt:
    name: "alacritty"
  tags:
    - alacritty
- name: Clone alacritty dracula theme
  git:
    repo: https://github.com/dracula/alacritty
    dest: ~/dracula-themes/alacritty
  tags:
    - dracula-theme
    - zsh
