- name: Install Core ubuntu packages
  become: true
  apt:
    name:
      - software-properties-common
      - curl
      - git
      - build-essential
      - sudo
      - i3
  tags:
    - ubuntu

- name: Remove Gnome Desktop Dock
  apt:
    pkg: gnome-shell-extension-ubuntu-dock
    state: absent
  become: true
