- name: Install zsh packages
  become: true
  apt:
    name: ["zsh", "fonts-powerline", "tmux"]
  tags:
    - zsh
- name: Change shell
  become: true
  shell: chsh -s `which zsh`
  tags:
    - zsh
- name: Install ohmyzsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --keep-zshrc
  tags:
    - zsh
- name: Install zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  tags:
    - zsh
- name: Install zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
  tags:
    - zsh
- name: Clone fzf
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: ~/.fzf
  tags:
    - zsh
- name: Install fzf
  shell: ~/.fzf/install
  tags:
    - zsh
- name: Clone zsh dracula theme
  git:
    repo: https://github.com/dracula/zsh.git
    dest: ~/dracula-themes/zsh
  tags:
    - zsh
- name: Create symlink for dracula theme
  file:
    src: ~/dracula-themes/zsh/dracula.zsh-theme
    dest: ~/.oh-my-zsh/themes/dracula.zsh-theme
    state: link
  tags:
    - dracula-theme
    - zsh
