- name: install docker deps
  become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

- name: add docker gpg key
  become: true
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --yes --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

- name: add docker ppa
  become: true
  apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable

- name: install docker
  become: true
  apt:
    name:
      - docker-ce

- name: add to docker group
  become: true
  shell: usermod -aG docker {{ lookup('env', 'USER') }}
