- name: ohmyzsh exists
  stat:
    path: ~/.oh-my-zsh
  register: ohmyzsh

- name: install ohmyzsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --keep-zshrc
  when: not ohmyzsh.stat.exists

- name: install nvm
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  args:
    creates: ~/.nvm/nvm.sh
  when: ansible_distribution == 'Ubuntu'

- name: install node lts
  shell: source ~/.nvm/nvm.sh && nvm install --lts
  args:
    executable: /bin/bash
  when: ansible_distribution == 'Ubuntu'

- name: install node lts
  shell: source /usr/share/nvm/init-nvm.sh && nvm install --lts
  args:
    executable: /bin/bash
  when: ansible_distribution == 'Archlinux'

- name: clone fzf
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: ~/.fzf
  when: ansible_distribution == 'Ubuntu'

- name: install fzf
  shell: ~/.fzf/install
  when: ansible_distribution == 'Ubuntu'

- name: zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

- name: zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting