---
- name: apt facts
  package_facts:
    manager: auto

- name: remove snap
  include_tasks:
    file: remove-snap.yml
  when: "ansible_distribution == 'Ubuntu' and 'snap' in ansible_facts.packages"

- name: ubuntu
  include_tasks:
    file: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: archlinux
  include_tasks:
    file: archlinux.yml
  when: ansible_distribution == 'Archlinux'

- name: dracula
  include_tasks:
    file: dracula.yml

- name: git-repos
  include_tasks:
    file: git-repos.yml
