---
- name: ubuntu
  include_tasks:
    file: ubuntu.yml
    apply:
      tags:
        - always
  tags: always

- name: alacritty
  include_tasks:
    file: alacritty.yml
    apply:
      tags:
        - alacritty
  tags:
    - alacritty

- name: dbeaver
  include_tasks:
    file: dbeaver.yml
    apply:
      tags:
        - dbeaver
  tags:
    - dbeaver

- name: docker
  include_tasks:
    file: docker.yml
    apply:
      tags:
        - docker
  tags:
    - docker

- name: stow
  include_tasks:
    file: stow.yml
    apply:
      tags:
        - stow
  tags:
    - stow

- name: firefox
  include_tasks:
    file: firefox.yml
    apply:
      tags:
        - firefox
  tags:
    - firefox

- name: nvm
  include_tasks:
    file: nvm.yml
    apply:
      tags:
        - nvm
  tags:
    - nvm

- name: zsh
  include_tasks:
    file: zsh.yml
    apply:
      tags:
        - zsh
  tags:
    - zsh

- name: tmux
  include_tasks:
    file: tmux.yml
    apply:
      tags:
        - tmux
  tags:
    - tmux