---
- name: ubuntu
  include_tasks:
    file: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: dracula
  include_tasks:
    file: dracula.yml
    apply:
      tags:
        - dracula
  tags:
    - dracula

- name: git-repos
  include_tasks:
    file: git-repos.yml
    apply:
      tags:
        - git-repos
  tags:
    - git-repos