test: ubuntu
on: [push]
jobs:
  ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Docker Build
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile.ubuntu 
          push: false
          tags: dotfiles-ubuntu:latest
      - run: docker run dotfiles-ubuntu:latest ansible-playbook -t install,dotfiles local.yml
  archlinux:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Docker Build
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile.archlinux 
          push: false
          tags: dotfiles-archlinux:latest
      - run: docker run dotfiles-archlinux:latest ansible-playbook -t install,dotfiles local.yml