name: ubuntu
on: [push]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Docker Build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: dotfiles-ubuntu:latest
      - run: docker run dotfiles-ubuntu:latest
     